Iter5
pavelborisofff/go-metrics pull request #5
Opened 2023-10-09 09:29 UTC by pavelborisofff

2023-10-10 22:06 UTC, vovean requested changes

2023-10-10 22:06 UTC, vovean commented on Makefile
> +git-checkout:
кажется, эта команда заставляет тебя печатать больше, чем если бы использовать гит напрямую xD

2023-10-10 22:06 UTC, vovean commented on cmd/agent/main.go
> +	reportIntervalDef = 10
time.Duration

2023-10-10 22:06 UTC, vovean commented on cmd/agent/main.go
> +	reportInterval int
time.Duration

2023-10-10 22:06 UTC, vovean commented on cmd/server/main.go
> +	htmlBody      = `
стоит вынести в отдельный файл и записывать в string переменную через //go:embed

2023-10-10 22:06 UTC, vovean commented on cmd/server/main.go
> +	GaugeStorage   map[string]Gauge   `json:"gauge"`
конкурентный доступ к мапам на запись из хендлеров приведет к ошибке хуже паники, из такой ошибки нельзя сделать recover. 

Нужно добавить мьютексы

2023-10-10 22:06 UTC, vovean commented on cmd/agent/main.go
> +	GaugeStorage   map[string]Gauge   `json:"gauge"`
конкурентный доступ на запись и чтение из мап. Нужен мьютекс

2023-10-10 22:06 UTC, vovean commented on cmd/agent/main.go
> +	v := reflect.ValueOf(m)
рефлексия - крайне медленно и потребляет заметно больше ресурсов, чем прямое обращение к полю. Реальные компании точно не хотят тратить свои вычислительные ресурсы на сборщик метирик, так что он должен быть как можно "легче"

2023-10-10 22:06 UTC, vovean commented on cmd/agent/main.go
> +		reportIntervalFlag int
https://pkg.go.dev/flag#Duration

2023-10-10 22:06 UTC, vovean commented on cmd/agent/main.go
> +	if pollInterval == 0 {
а если меньше 0?)

2023-10-10 22:06 UTC, vovean commented on cmd/server/main.go
> +		return
отправить клиенту ошибку?

2023-10-10 22:06 UTC, vovean commented on cmd/server/main.go
> +			http.Error(res, `Not found`, http.StatusNotFound)
в коде выше для ошибок используются двойные кавычки (строки 125, 139). Не стоит мешать стили кавычек. Я бы везде использовал двойные

2023-10-10 22:06 UTC, vovean commented on cmd/server/main_test.go
> +			w := httptest.NewRecorder()
отличное использование httptest

2023-10-10 22:06 UTC, vovean commented on internal/storage/storage.go
> +	GaugeStorage   map[string]Gauge   `json:"gauge"`
мьютекс)

2023-10-11 05:51 UTC, pavelborisofff commented on Makefile
> +git-checkout:
Длинеее, ага :) мейкфайл больше чтобы всегда можно было глянуть синтаксис команд используемых, который (внезапно) может вылететь из головы, особенно если с гитом из-за лени через IDE работаешь. Так что пусть лучше будет.

2023-10-11 05:54 UTC, pavelborisofff commented on cmd/agent/main.go
> +	v := reflect.ValueOf(m)
И как в таком случае правильно поступить? Интернеты могут много чего подсказать, но от best practice это может быть очень далеко.

2023-10-14 11:47 UTC, pavelborisofff commented on cmd/agent/main.go
> +	GaugeStorage   map[string]Gauge   `json:"gauge"`
Решил через тикеры и каналы, обошлось без мьютексов (еслм флаг -race не врёт при использовании)

2023-10-14 11:59 UTC, pavelborisofff commented on cmd/agent/main.go
> +		reportIntervalFlag int
Резонно :D 

Сделал проверку < 1

2023-10-14 11:59 UTC, pavelborisofff commented on cmd/agent/main.go
> +	if pollInterval == 0 {
Резонно :D

Сделал проверку < 1

2023-10-14 11:59 UTC, pavelborisofff commented on cmd/agent/main.go
> +		reportIntervalFlag int
Использовал flag.DurationVar

2023-10-14 12:15 UTC, pavelborisofff commented on cmd/agent/main.go
> +	v := reflect.ValueOf(m)
Сделал прямым обращением к полям МемСтата. 

Нооо… вопрос. В Питоне (да и в ЖС, и даже ТС, пожалуй) я бы вынес такие вещи в отдельный конфиг — кто знает, какую метрику потребуется использовать, и чтобы потом по коду не шарится, а функция циклом была (вот как я первоначлаьно сделал).

Тут я не понимаю:
1) Как можно вынести это отдельной мапой? И нужно ли вообще?
2) Нет быстрых способов обхода по строковым названиям структур?

2023-10-14 12:16 UTC, pavelborisofff commented on cmd/agent/main.go
> +	reportInterval int
изменил тип

2023-10-14 12:16 UTC, pavelborisofff commented on cmd/agent/main.go
> +	reportIntervalDef = 10
изменил тип

2023-10-14 12:19 UTC, pavelborisofff commented on cmd/server/main.go
> +			http.Error(res, `Not found`, http.StatusNotFound)
Да, по привычке после JS бэктики для строк использую, для форматирования `%{varName}`
Исправил

2023-10-14 12:23 UTC, pavelborisofff commented on cmd/server/main.go
> +		return
Тут же 500 ошибка?

2023-10-14 14:38 UTC, pavelborisofff commented on cmd/server/main.go
> +	htmlBody      = `
Вся красота Go пропала с этим embed, выглядит не очевидно и как какая-то магия :С

2023-10-14 14:38 UTC, pavelborisofff commented on cmd/server/main.go
> +	GaugeStorage   map[string]Gauge   `json:"gauge"`
Добавил

2023-10-15 10:51 UTC, pavelborisofff commented on cmd/agent/main.go
> +		reportIntervalFlag int
нет, вернул как было на инты

Падали тесты, потому что передаются именно Инты в аргументы строки и в переменные окружения (числа 1, 2, 10 и т.д.)

Из документации, внутри flag/flag.go
`Duration flags accept any input valid for time.ParseDuration`

Смотрим в time/format.go
`// Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
func ParseDuration(s string) (Duration, error) {
	// [-+]?([0-9]*(\.[0-9]*)?[a-z]+)+`
	
И ниже там же
`		// Consume unit.
		i := 0
		for ; i < len(s); i++ {
			c := s[i]
			if c == '.' || '0' <= c && c <= '9' {
				break
			}
		}
		if i == 0 {
			return 0, errors.New("time: missing unit in duration " + quote(orig))
		}
		u := s[:i]
		s = s[i:]
		unit, ok := unitMap[u]`
	
По регулярке и по обработке видно, что units обязательные как строка, т.е. флаг типа -r=10 не пройдёт в тестах при использовании flag.Duration

2023-10-18 20:11 UTC, vovean approved these changes

2023-10-18 20:11 UTC, vovean commented on cmd/server/main.go
> +		return
да

2023-10-18 21:20 UTC, merged