Iter9
pavelborisofff/go-metrics pull request #9
Opened 2023-10-30 19:10 UTC by pavelborisofff

2023-10-30 20:48 UTC, vovean requested changes

2023-10-30 20:48 UTC, vovean commented on cmd/server/main.go
> +func init() {
init использовать - не лучшая практика, хотя бы потому, что ты теперь не сможешь нормально протестировать этот пакет

2023-10-30 20:48 UTC, vovean commented on cmd/server/main.go
> +		log.Println("Metrics restored")
какой-нить пакет логирования? zap / zerolog/ logrus / ...

2023-10-30 20:48 UTC, vovean commented on internal/gzip/gzip.go
> +	if statusCode < 300 {
1xx коды тоже подходят, получается?

2023-10-30 20:48 UTC, vovean commented on internal/handlers/handlers.go
> +		http.Error(res, msg, http.StatusBadRequest)
вот тут забыл return, потому что без него ты выйдешь из этого switch-case и код ошибки затрется на 74 строке

2023-10-30 20:48 UTC, vovean commented on internal/handlers/handlers.go
> +	defer req.Body.Close()
не имеет смысл закрывать body реквеста на стороне сервера. На стороне клиента мы это делаем, чтобы побыстрее отпустить коннект и отдать в распоряжение ОС. На стороне сервера ты коннект никак не отпустишь, потому что тебе туда еще ответ записывать

2023-10-30 20:48 UTC, vovean commented on internal/handlers/handlers.go
> +		log.Fatal(msg)
fatal завершит исполнение программы мгновенно. Сомневаюсь, что это адекватная реакция на ошибку)

2023-10-30 20:48 UTC, vovean commented on internal/handlers/handlers.go
> +	log.Println(write)
логируешь количество записанных байт? Думаешь, такой лог принесет много пользы?

2023-10-30 20:48 UTC, vovean commented on internal/handlers/handlers.go
> +				return
тут, кажется, получится код 200, потому что никакой ошибки ты не установил, а обработку закончил

2023-10-30 20:48 UTC, vovean commented on internal/handlers/handlers.go
> +			http.Error(res, "Not found", http.StatusNotFound)
return

2023-10-30 20:48 UTC, vovean commented on internal/handlers/handlers.go
> +			*m.Value = float64(v)
классный способ присвоить значение указателю. Я чаще всего вижу через временную переменную)

2023-10-30 20:48 UTC, vovean commented on internal/logger/logger.go
> +	defer logger.Sync()
logger.Sync() нужно вызывать при завершении приложения, чтобы он записал, все что еще не записано и лежит в буфферах. В твоем же случае эта функция вызовется в конце функции InitLogger(), а при завершении работы приложения ничего не вызовется

2023-10-30 20:48 UTC, vovean commented on internal/logger/logger.go
> +func Middleware(next http.Handler) http.Handler {
не самое понятное название. Мидлварей бывает много. Что делает твоя мидлварь? Стоит отразить это в названии

2023-10-30 20:48 UTC, vovean commented on internal/storage/agentStorage.go
> +	return nil
зачем в функции возвращается ошибка, если она всегда nil?

2023-10-30 20:48 UTC, vovean commented on internal/storage/agentStorage.go
> +func (s *AgentStorage) SendJSONMetric(m Metrics, serverAddr string) {
а вот здесь возвращать ошибку не помешало бы

2023-10-30 20:48 UTC, vovean commented on internal/storage/agentStorage.go
> +/*func (s *AgentStorage) SendJSONMetric(m Metrics, serverAddr string) {
не стоит держать закомментированный код в мастере

2023-10-30 20:48 UTC, vovean commented on internal/storage/serverStorage.go
> +	once.Do(func() {
отлично, что используешь once

2023-10-30 20:48 UTC, vovean commented on internal/storage/serverStorage.go
> +		}
чтобы уменьшить уровень вложенности можно вынести этт иф после проверки длины data

2023-10-31 16:32 UTC, pavelborisofff commented on internal/gzip/gzip.go
> +	if statusCode < 300 {
Код прям целиком из урока брал.
Для сотых кодов да, смысла нет сжатие использовать, конечно

2023-10-31 16:37 UTC, pavelborisofff commented on internal/storage/serverStorage.go
> +		}
Вынес

2023-10-31 16:49 UTC, pavelborisofff commented on internal/storage/agentStorage.go
> +func (s *AgentStorage) SendJSONMetric(m Metrics, serverAddr string) {
Логично :) поправил

2023-10-31 16:50 UTC, pavelborisofff commented on internal/storage/agentStorage.go
> +	return nil
Теперь не всегда nil

2023-10-31 16:54 UTC, pavelborisofff commented on internal/handlers/handlers.go
> +		http.Error(res, msg, http.StatusBadRequest)
Точно. И кейсы поменял на типы из стораджа

2023-10-31 16:56 UTC, pavelborisofff commented on internal/handlers/handlers.go
> +	defer req.Body.Close()
То есть, закрытие бади всё равно есть, но оно где-то в глубинах пакета http?

2023-10-31 17:02 UTC, pavelborisofff commented on internal/handlers/handlers.go
> +		log.Fatal(msg)
да. пожалуй, не стоит

2023-10-31 17:03 UTC, pavelborisofff commented on internal/handlers/handlers.go
> +	log.Println(write)
убрал

2023-10-31 17:15 UTC, pavelborisofff commented on internal/handlers/handlers.go
> +				return
Да, пропустил

2023-10-31 17:19 UTC, pavelborisofff commented on internal/logger/logger.go
> +	defer logger.Sync()
Ммм… то есть, это стоит вынести вообще в мейн?

2023-10-31 17:27 UTC, pavelborisofff commented on cmd/server/main.go
> +func init() {
О, а вот тут тогда вопросы:
1) В каких случаях используется тогда? В Пайтоне, например, удобно в __init__ запихивать иницаицию всего, что в модуле есть. Или более частный случай, типа FastAPI @app.on_event("startup"), куда не только коннект к БД, но и чтение настроек/окружения кладут. Тут показлось логичным и общий стор инициализировать здесь
2) Что вообще и как тестировать в таких местах? Вроде особо и нечего, не понимаю, какие кейсы тут можно придумать

2023-10-31 19:19 UTC, pavelborisofff commented on cmd/server/main.go
> +		log.Println("Metrics restored")
переписал логи на zap

2023-10-31 19:20 UTC, pavelborisofff commented on internal/handlers/handlers.go
> +			http.Error(res, "Not found", http.StatusNotFound)
ЗАпутался с ретурнами, когда они ттут обоснованы, когда нет

2023-10-31 19:20 UTC, pavelborisofff commented on internal/logger/logger.go
> +func Middleware(next http.Handler) http.Handler {
Переименовал

2023-11-04 17:18 UTC, vovean approved these changes

2023-11-04 17:18 UTC, vovean commented on cmd/server/main.go
> +	log.Info(msg)
зачем использовать zap, который предоставляет структурное логирование (zap.String(), zap.Int() и т д), если все равно продолжать делать Sprintf? Кажется, нет смысла. Может переделать на правильное использование zap? И во всех остальных местах тоже

2023-11-04 17:18 UTC, vovean commented on internal/gzip/gzip.go
> +		return nil, err
если функция возвращает несколько ошибок, то хорошей практикой будет враппать их. А то непонятно, какая именно часть функции вернула ошибку

2023-11-04 17:18 UTC, vovean commented on internal/handlers/handlers.go
> +			log.Debug(msg)
почему дебаг? варн подошел бы лучше - тут же ошибка

2023-11-04 17:18 UTC, vovean commented on internal/storage/serverStorage.go
> +	data, err := json.MarshalIndent(s, "", "   ")
сюда тоже мьютекс нужно, ты же все мапы целиком вычитываешь для маршалинга

2023-11-04 17:18 UTC, vovean commented on internal/storage/serverStorage.go
> +func (s *MemStorage) FromFile(f string) error {
вроде, это используется только при старте, но тут мьютекс тоже лишним не будет

2023-11-12 18:42 UTC, pavelborisofff commented on cmd/server/main.go
> +	log.Info(msg)
Остался старый логе где-то, уберу

2023-11-12 18:43 UTC, pavelborisofff commented on internal/gzip/gzip.go
> +		return nil, err
Хм, вот тут не понятно, спрошу на созвоне :)

2023-11-12 18:43 UTC, pavelborisofff commented on internal/handlers/handlers.go
> +			log.Debug(msg)
Варн, точно. Это как бы не ошибка сервака, если ему кривые данные прилетели

2023-11-12 18:44 UTC, pavelborisofff commented on internal/storage/serverStorage.go
> +func (s *MemStorage) FromFile(f string) error {
и тут тоже

2023-11-12 18:44 UTC, pavelborisofff commented on internal/storage/serverStorage.go
> +	data, err := json.MarshalIndent(s, "", "   ")
Добавлю

2023-11-12 18:44 UTC, merged